import React from 'react';
import Layout from '@theme/Layout';
import Link from '@docusaurus/Link';
import Head from '@docusaurus/Head';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

export default function Tags() {
  const { siteConfig } = useDocusaurusContext();

  const vibeCodingTags = [
    {
      name: 'vibe-coding',
      description: 'The core concept of using AI and large language models to generate code through natural language prompts, coined by Andrej Karpathy.',
      link: '/tags/vibe-coding',
    },
    {
      name: 'ai-assisted-programming',
      description: 'Programming approach where AI tools help developers write, debug, and refine code.',
      link: '/tags/ai-assisted-programming',
    },
    {
      name: 'llm-code',
      description: 'Code generated by Large Language Models through natural language instructions.',
      link: '/tags/llm-code',
    },
    {
      name: 'prompt-engineering',
      description: 'The practice of crafting effective prompts to guide AI in generating useful code.',
      link: '/tags/prompt-engineering',
    },
    {
      name: 'natural-language-programming',
      description: 'Using everyday language instead of programming syntax to create software.',
      link: '/tags/natural-language-programming',
    },
    {
      name: 'andrej-karpathy',
      description: 'Content related to Andrej Karpathy, who coined the term "vibe coding" in 2025.',
      link: '/tags/andrej-karpathy',
    },
  ];

  return (
    <>
      <Head>
        <title>Vibe Coding Tags | {siteConfig.title}</title>
        <meta name="description" content="Explore our content organized by vibe coding topics, including AI-assisted programming, prompt engineering, and natural language programming." />
        <meta name="keywords" content="vibe coding, AI-assisted programming, LLM-generated code, natural language programming, prompt engineering, Andrej Karpathy" />
      </Head>
      <Layout title="Vibe Coding Tags">
        <main className="container margin-vert--xl">
          <div className="row">
            <div className="col col--8 col--offset-2">
              <h1>Vibe Coding Topics</h1>
              <p className="margin-bottom--lg">
                Browse our content by vibe coding related topics. Explore AI-assisted programming techniques, prompt engineering strategies, and more.
              </p>

              <div className="margin-bottom--xl">
                {vibeCodingTags.map((tag) => (
                  <div key={tag.name} className="card margin-bottom--md">
                    <div className="card__body">
                      <h3>
                        <Link to={tag.link}>#{tag.name}</Link>
                      </h3>
                      <p>{tag.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </main>
      </Layout>
    </>
  );
}